// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vestigia.Infrastructure.Data;

#nullable disable

namespace Vestigia.Infrastructure.Migrations
{
    [DbContext(typeof(VestigiaContext))]
    [Migration("20260208193547_AtualizandoDominio")]
    partial class AtualizandoDominio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoriaTransacao", b =>
                {
                    b.Property<Guid>("CategoriasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransacoesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriasId", "TransacoesId");

                    b.HasIndex("TransacoesId");

                    b.ToTable("CategoriaTransacao");
                });

            modelBuilder.Entity("TransacaoTag", b =>
                {
                    b.Property<Guid>("IdTag")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTransacao")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdTag", "IdTransacao");

                    b.HasIndex("IdTransacao");

                    b.ToTable("TransacaoTag");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Lido")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Lembrete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Lembretes");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.LogSaldo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdConta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("MesReferencia")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("IdConta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LogSaldos");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Meta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Prazo")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.RelatorioIA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntidadeRelacionada")
                        .HasColumnType("int");

                    b.Property<Guid>("IdEntidadeRelacionada")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RelatorioIAs");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdConta")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("IdTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdConta");

                    b.ToTable("Transacaos");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CategoriaTransacao", b =>
                {
                    b.HasOne("Vestigia.Domain.Entities.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vestigia.Domain.Entities.Transacao", null)
                        .WithMany()
                        .HasForeignKey("TransacoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TransacaoTag", b =>
                {
                    b.HasOne("Vestigia.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("IdTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vestigia.Domain.Entities.Transacao", null)
                        .WithMany()
                        .HasForeignKey("IdTransacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Alerta", b =>
                {
                    b.HasOne("Vestigia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("Vestigia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Categorias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Vestigia.Domain.ValueObjects.Nome", "Nome", b1 =>
                        {
                            b1.Property<Guid>("CategoriaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Nome");

                            b1.HasKey("CategoriaId");

                            b1.ToTable("Categorias");

                            b1.WithOwner()
                                .HasForeignKey("CategoriaId");
                        });

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Conta", b =>
                {
                    b.HasOne("Vestigia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Contas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Vestigia.Domain.ValueObjects.Nome", "NomeConta", b1 =>
                        {
                            b1.Property<Guid>("ContaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("NomeConta");

                            b1.HasKey("ContaId");

                            b1.ToTable("Contas");

                            b1.WithOwner()
                                .HasForeignKey("ContaId");
                        });

                    b.OwnsOne("Vestigia.Domain.ValueObjects.Monetario", "Saldo", b1 =>
                        {
                            b1.Property<Guid>("ContaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Saldo");

                            b1.HasKey("ContaId");

                            b1.ToTable("Contas");

                            b1.WithOwner()
                                .HasForeignKey("ContaId");
                        });

                    b.OwnsOne("Vestigia.Domain.ValueObjects.Monetario", "SaldoInicial", b1 =>
                        {
                            b1.Property<Guid>("ContaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SaldoInicial");

                            b1.HasKey("ContaId");

                            b1.ToTable("Contas");

                            b1.WithOwner()
                                .HasForeignKey("ContaId");
                        });

                    b.Navigation("NomeConta")
                        .IsRequired();

                    b.Navigation("Saldo")
                        .IsRequired();

                    b.Navigation("SaldoInicial")
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Lembrete", b =>
                {
                    b.HasOne("Vestigia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Lembretes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Vestigia.Domain.ValueObjects.Nome", "Nome", b1 =>
                        {
                            b1.Property<Guid>("LembreteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Nome");

                            b1.HasKey("LembreteId");

                            b1.ToTable("Lembretes");

                            b1.WithOwner()
                                .HasForeignKey("LembreteId");
                        });

                    b.OwnsOne("Vestigia.Domain.ValueObjects.Monetario", "Valor", b1 =>
                        {
                            b1.Property<Guid>("LembreteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Valor");

                            b1.HasKey("LembreteId");

                            b1.ToTable("Lembretes");

                            b1.WithOwner()
                                .HasForeignKey("LembreteId");
                        });

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Valor")
                        .IsRequired();
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.LogSaldo", b =>
                {
                    b.HasOne("Vestigia.Domain.Entities.Conta", "Conta")
                        .WithMany("LogSaldos")
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vestigia.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Vestigia.Domain.ValueObjects.Monetario", "SaldoFechamento", b1 =>
                        {
                            b1.Property<Guid>("LogSaldoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("LogSaldoId");

                            b1.ToTable("LogSaldos");

                            b1.WithOwner()
                                .HasForeignKey("LogSaldoId");
                        });

                    b.Navigation("Conta");

                    b.Navigation("SaldoFechamento")
                        .IsRequired();
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Meta", b =>
                {
                    b.HasOne("Vestigia.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Metas")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vestigia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Metas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Vestigia.Domain.ValueObjects.Nome", "Nome", b1 =>
                        {
                            b1.Property<Guid>("MetaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Nome");

                            b1.HasKey("MetaId");

                            b1.ToTable("Metas");

                            b1.WithOwner()
                                .HasForeignKey("MetaId");
                        });

                    b.OwnsOne("Vestigia.Domain.ValueObjects.Monetario", "ValorAlcancado", b1 =>
                        {
                            b1.Property<Guid>("MetaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ValorAlcancado");

                            b1.HasKey("MetaId");

                            b1.ToTable("Metas");

                            b1.WithOwner()
                                .HasForeignKey("MetaId");
                        });

                    b.OwnsOne("Vestigia.Domain.ValueObjects.Monetario", "ValorAlvo", b1 =>
                        {
                            b1.Property<Guid>("MetaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ValorAlvo");

                            b1.HasKey("MetaId");

                            b1.ToTable("Metas");

                            b1.WithOwner()
                                .HasForeignKey("MetaId");
                        });

                    b.Navigation("Categoria");

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("ValorAlcancado")
                        .IsRequired();

                    b.Navigation("ValorAlvo")
                        .IsRequired();
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.RelatorioIA", b =>
                {
                    b.HasOne("Vestigia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Relatorios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Vestigia.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Vestigia.Domain.ValueObjects.Nome", "Nome", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Nome");

                            b1.HasKey("TagId");

                            b1.ToTable("Tags");

                            b1.WithOwner()
                                .HasForeignKey("TagId");
                        });

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("Vestigia.Domain.Entities.Conta", "Conta")
                        .WithMany("Transacoes")
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("Vestigia.Domain.ValueObjects.Monetario", "Valor", b1 =>
                        {
                            b1.Property<Guid>("TransacaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Valor");

                            b1.HasKey("TransacaoId");

                            b1.ToTable("Transacaos");

                            b1.WithOwner()
                                .HasForeignKey("TransacaoId");
                        });

                    b.Navigation("Conta");

                    b.Navigation("Valor")
                        .IsRequired();
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Usuario", b =>
                {
                    b.OwnsOne("Vestigia.Domain.ValueObjects.Nome", "Nome", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Nome");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Vestigia.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Metas");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Conta", b =>
                {
                    b.Navigation("LogSaldos");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("Vestigia.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Categorias");

                    b.Navigation("Contas");

                    b.Navigation("Lembretes");

                    b.Navigation("Metas");

                    b.Navigation("Relatorios");
                });
#pragma warning restore 612, 618
        }
    }
}
